---
apiVersion: v1
kind: Pod
metadata:
   name: use-cm-volume-pod
spec:
  containers:
  - name: test-cm-by-volume
    image: busybox
    # 因为把cm-demo3这个ConfigMap资源对象中的"redis.conf"文件填入到了"/etc/config"这个目录下,所以这里能打印出"redis.conf"的内容
    command: ["/bin/sh", "-c", "cat /etc/config/redis.conf"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  # 因为volumes不属于任何一个容器,所以和containers平级.同样volume可以有多个,所以volume是个数组
  volumes:
  - name: config-volume
    configMap:
      # cm-demo3这个ConfigMap资源对象有"redis.conf"和"mysql.conf"两个文件,这两个文件都会被填入到"/etc/config"这个目录下
      name: cm-demo3