---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aaron-role
  namespace: kube-system
rules:
- apiGroups:
  - ""
  - apps
  resources:
  - pods
  - deployments
  - replicasets
  verbs:
  - '*'