apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}  # 配置自签名的证书机构类型
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  dnsNames:
  - example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned

# 配置参考
#  Issuer:
#    https://cert-manager.io/docs/concepts/issuer/
#    https://cert-manager.io/docs/configuration/
#    https://cert-manager.io/docs/configuration/selfsigned/ 
#  Certificate：https://cert-manager.io/docs/concepts/certificate/