#模拟api服务:
---
apiVersion: v1
kind: Pod
metadata:
  name: test-api
  labels:
    app: test-pod
spec:
  containers:
  - name: test-api
    image: busybox
    imagePullPolicy: IfNotPresent
    # 打印环境变量
    command: ["/bin/sh", "-c", "env"]
