---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-http-demo
  labels:
    app: liveness
spec:
  containers:
  - name: liveness-probe-http-demo
    image: cnych/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3  