---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-demo
  labels:
    app: rc
spec:
  replicas: 3
  selector:
    app: rc
  template:
    metadata:
      labels:
        app: rc
    spec:
      containers:
      - name: nginx-name
        image: nginx
        ports:
        - containerPort: 80

