apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: kube-ops
data:
  grafana.ini: |
    [server]
    root_url = http://192.168.32.100:31281
    [smtp]
    enabled = true
    host = smtp.163.com:25
    user = kkk_en@163.com
    password = WZOGCXPPOPOSQWMJ
    skip_verify = true
    from_address = kkk_en@163.com
    [alerting]
    enabled = true
    execute_alerts = true