---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aaron-sa-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["*"]