---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc2-nfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    # 指定PVC去匹配一个"app=nfs"的PV
    matchLabels:
      app: nfs