---
apiVersion: v1
kind: ConfigMap
metadata:
   name: traefik-dynamic-conf
data:
  traefik.yaml: |
    # Traefik Dynamic Configuration
    http:
      routers:
        dashboard:
          rule: Host(`traefik.aaron.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
          service: api@internal
          middlewares:
            - auth
      middlewares:
        auth:
          basicAuth:
            users:
              - "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"
              - "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"