---
apiVersion: v1
kind: Pod
metadata:
  name: test-secret-docker-registry-pod
spec:
  containers:
  - name: foo
    # 私有仓库镜像,默认私有仓库只需要用 docker login 认证
    image: 192.168.1.100:5000/test:v1
  imagePullSecrets:
  - name: my-docker-registry