---
apiVersion: v1
kind: Pod
metadata:
   name: use-secret-by-volume-pod
spec:
  containers:
  - name: use-secret-by-volume
    image: busybox
    # 挂载进去会把Secret对象里面的数据变成文件,有多少条数据就会有多少个文件
    command: ["/bin/sh", "-c", "ls /etc/secrets"]
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
  volumes:
  - name: secrets
    secret:
      secretName: secret-base64