---
apiVersion: v1
kind: Pod
metadata:
   name: use-secret-by-env-pod
spec:
  containers:
  - name: use-secret-by-env
    image: busybox
    command: ["/bin/sh", "-c", "env"]
    env:
    - name: USERNAME
      valueFrom:
        # secretKeyRef 表示从Secret对象中获取
        secretKeyRef:
          # 指定Secret对象
          name: secret-base64
          key: username
    - name: PASSWORD
      valueFrom:
        # secretKeyRef 表示从Secret对象中获取
        secretKeyRef:
          # 指定Secret对象
          name: secret-base64
          key: password