---
apiVersion: v1
kind: Pod
metadata:
   name: use-secret-by-volume-pod2
spec:
  containers:
  - name: use-secret-by-volume2
    image: busybox
    command: ["/bin/sh", "-c", "cat /etc/secrets/usr/detail/userinfo.conf"]
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
  volumes:
  - name: secrets
    secret:
      secretName: secret-base64
      # 把Secret对象挂载到指定的文件,在secretName下⾯添加items,指定key和path
      items:
      - key: username
        path: usr/detail/userinfo.conf
     